---
driver:
  name: vagrant
provisioner:
  name: chef_solo
platforms:
  - name: ubuntu-12.04
    driver_config:
      box: precise64
      box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box
      provider: virtualbox
      customize:
        memory: 1024
      network:
        - ["private_network", {ip: "192.168.50.5"}]
      use_vagrant_provision: true
      require_chef_omnibus: true
      forward_agent: true
suites:
  - name: default
    data_bags_path: chef/data_bags
    data_path: test/integration/data
    roles_path: chef/sites
    provisioner:
      client_rb:
        environment: development
    run_list:
      role[example]
    attributes:
      drupal:
        deploy:
          action:
            - deploy
            - install
  - name: make
    data_bags_path: chef/data_bags
    data_path: test/integration/data
    roles_path: chef/sites
    provisioner:
      client_rb:
        environment: development
    run_list:
      role[example]
    attributes:
      drupal:
        deploy:
          action:
            - deploy
            - install
          releases: 1
        drush_make:
          api: 2
          files:
            core: "drupal-org-core.make"
          template: true
  - name: import
    data_bags_path: chef/data_bags
    data_path: test/integration/data
    roles_path: chef/sites
    provisioner:
      client_rb:
        environment: development
    run_list:
      role[example]
    attributes:
      drupal:
        deploy:
          action:
            - deploy
            - import
        drupal:
          settings:
            db_file: "/tmp/kitchen/data/test.sql"

